title: Muhammad Haidar Khan
logo: headshot_circle.png
description: I'm a data storyteller, weaving insights into narratives that drive impact and innovation. 📊✨
show_downloads: FALSE
theme: jekyll-theme-caymaN
