plugins:
  - jekyll-remote-theme

remote_theme: ngzhio/jekyll-theme-hamilton
title: Muhamad Haidar Khan
description: Thank You For Visting! :)
avatar: mhaidarkhan.github.io/haidar.png
subscribe: false
location: Lahore, Punjab, Pakistan
author: Muhammad Haidar Khan
skin: midnight
social:
  name: Muhamad Haidar Khan
  links:
    - https://linkedin.com/in/haidarkhan
    - https://github.com/mhaidarkhan
    - https://mhaidarkhan.github.io/assets/resume.pdf
