plugins:
  - jekyll-remote-theme

remote_theme: ngzhio/jekyll-theme-hamilton
title: Muhamad Haidar Khan
description: Thank You For Visiting! :)
avatar: https://avatars.githubusercontent.com/u/132541949?s=400&u=51f6429969ae06e9127340334bba8c83b068c3d3&v=4
subscribe: false
location: Lahore, Punjab, Pakistan
author: Haidar
skin: midnight
social:
  name: Haidar
  links:
    - https://linkedin.com/in/haidarkhan
    - https://github.com/mhaidarkhan
    - https://mhaidarkhan.github.io/assets/resume.pdf
