plugins:
  - jekyll-remote-theme

remote_theme: ngzhio/jekyll-theme-hamilton
title: Muhamad Haidar Khan
description: mhkvlog@gmail.com
avatar: /assets/me.png
subscribe: false
location: Lahore, Punjab, Pakistan
author: Muhammad Haidar Khan
skin: midnight
social:
  name: Muhammad Haidar Khan
  links:
    - https://linkedin.com/in/haidarkhan
    - https://github.com/mhaidarkhan

